### ISSUE TITLE
get colors from Xresources

### ISSUE THREAD

**Issue by aleprovencio** [5digits/dactyl#166]
The next i3 release will support this feature by using [this](https://github.com/Airblader/xcb-util-xrm) fresh new lib, could that be possible on pentadactyl?

**Comment by mrrhq** [comment]
It's a bad idea because it encourages dependency on X11. Wayland and eventually most terminal emulators following in Wayland's footsteps will not any Xresources, which leads me to think this dependency is a bad idea. Pentadactyl should still be configured with CSS styling, since it is in a browser anyway. You can use `:source` and select your style sheet to change the browser appearance, even using XUL. Thankfully, XUL has not phased out of Firefox just yet, but they are sure to replace it with something in the future.

**Comment by aleprovencio** [comment]
Yeah nowadays I do agree to that also, thanks.
